# OV7670 PCLK Period Constraint (25MHz = 40ns)




set_property IOSTANDARD LVCMOS33 [get_ports {led_0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports hdmi_oen_0]
set_property IOSTANDARD LVCMOS33 [get_ports ov7670_href_0]
set_property IOSTANDARD LVCMOS33 [get_ports ov7670_vsync_0]
set_property PACKAGE_PIN K14 [get_ports {ov7670_data_0[7]}]
set_property PACKAGE_PIN J14 [get_ports {ov7670_data_0[6]}]
set_property PACKAGE_PIN N15 [get_ports {ov7670_data_0[5]}]
set_property PACKAGE_PIN N16 [get_ports {ov7670_data_0[4]}]
set_property PACKAGE_PIN L14 [get_ports {ov7670_data_0[3]}]
set_property PACKAGE_PIN L15 [get_ports {ov7670_data_0[2]}]
set_property PACKAGE_PIN K16 [get_ports {ov7670_data_0[1]}]
set_property PACKAGE_PIN J16 [get_ports {ov7670_data_0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ov7670_data_0[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ov7670_data_0[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ov7670_data_0[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ov7670_data_0[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ov7670_data_0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ov7670_data_0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ov7670_data_0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ov7670_data_0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports ov7670_pclk_0]
set_property PACKAGE_PIN L20 [get_ports hdmi_oen_0]
set_property PACKAGE_PIN G20 [get_ports ov7670_href_0]
set_property PACKAGE_PIN G19 [get_ports ov7670_vsync_0]
set_property PACKAGE_PIN P20 [get_ports {led_0[3]}]
set_property PACKAGE_PIN N20 [get_ports {led_0[2]}]
set_property PACKAGE_PIN H16 [get_ports {hdmi_data_p_0[0]}]
set_property PACKAGE_PIN L16 [get_ports {hdmi_data_p_0[2]}]
set_property PACKAGE_PIN H15 [get_ports ov7670_pclk_0]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets ov7670_pclk_0_IBUF]

set_property IOSTANDARD TMDS_33 [get_ports hdmi_clk_p_0]
set_property IOSTANDARD TMDS_33 [get_ports hdmi_clk_n_0]
set_property IOSTANDARD LVCMOS33 [get_ports sys_clk_0]
set_property PACKAGE_PIN U18 [get_ports sys_clk_0]
set_property IOSTANDARD LVCMOS33 [get_ports sys_rst_n]
set_property PACKAGE_PIN W14 [get_ports sys_rst_n]
set_property IOSTANDARD TMDS_33 [get_ports {hdmi_data_p_0[2]}]
set_property IOSTANDARD TMDS_33 [get_ports {hdmi_data_n_0[2]}]
set_property IOSTANDARD TMDS_33 [get_ports {hdmi_data_p_0[1]}]
set_property IOSTANDARD TMDS_33 [get_ports {hdmi_data_n_0[1]}]
set_property IOSTANDARD TMDS_33 [get_ports {hdmi_data_p_0[0]}]
set_property IOSTANDARD TMDS_33 [get_ports {hdmi_data_n_0[0]}]
set_property PACKAGE_PIN K17 [get_ports {hdmi_data_p_0[1]}]

set_property IOSTANDARD LVCMOS33 [get_ports ov7670_xclk_0]
set_property PACKAGE_PIN G15 [get_ports ov7670_xclk_0]
set_property IOSTANDARD LVCMOS33 [get_ports ov7670_pwdn_0]
set_property IOSTANDARD LVCMOS33 [get_ports ov7670_reset_0]
set_property IOSTANDARD LVCMOS33 [get_ports ov7670_sioc_0]
set_property IOSTANDARD LVCMOS33 [get_ports ov7670_siod_0]
set_property PACKAGE_PIN M18 [get_ports ov7670_pwdn_0]
set_property PACKAGE_PIN M17 [get_ports ov7670_reset_0]
set_property PACKAGE_PIN J20 [get_ports ov7670_sioc_0]
set_property PACKAGE_PIN H20 [get_ports ov7670_siod_0]

set_property PACKAGE_PIN J18 [get_ports hdmi_clk_p_0]

set_property PACKAGE_PIN P16 [get_ports {led_0[1]}]
set_property PACKAGE_PIN P15 [get_ports {led_0[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports sys_rst_n_0]
set_property PACKAGE_PIN W14 [get_ports sys_rst_n_0]
set_property PULLUP TRUE [get_ports ov7670_siod_0]
set_property PULLUP TRUE [get_ports ov7670_sioc_0]
